# conda
name: venvOsee
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.2
  - pip
  - pip:
    - pip-tools
    - ipynb==0.5.1
    - streamlit==1.25.0
    - streamlit-aggrid
    - mysql-connector-python
    - SQLAlchemy==1.4.46
    - duckdb==1.0.0
  - pandas=1.2.2
  - numpy==1.19.2
  - seaborn==0.12.2
  - ipykernel
  - gdal=3.2.2
  - nbformat
